name: Workflow Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/*
      - .ci/tools/go.mod
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version-file: .ci/tools/go.mod
      - name: Install actionlint
        run: cd .ci/tools && go install github.com/rhysd/actionlint/cmd/actionlint
      - name: Run actionlint on workflow files
        run: actionlint -shellcheck=
